name: Deploy
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://saahild.com/ai-blog
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root
            PUBLIC_URL=/ai-blog bash ./deploy_project.sh ${{ github.event.repository.name }} ai-blog "npm install" "npm run build"
